{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "stoppablecontainer.serviceAccountName" . }}-controller
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "stoppablecontainer.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "stoppablecontainer.serviceAccountName" . }}-mount-helper
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "stoppablecontainer.labels" . | nindent 4 }}
{{- end }}
