apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: stoppablecontainer-mount-helper
  namespace: system
  labels:
    app.kubernetes.io/name: stoppablecontainer
    app.kubernetes.io/component: mount-helper
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: stoppablecontainer
      app.kubernetes.io/component: mount-helper
  template:
    metadata:
      labels:
        app.kubernetes.io/name: stoppablecontainer
        app.kubernetes.io/component: mount-helper
    spec:
      hostPID: true
      serviceAccountName: stoppablecontainer-mount-helper
      priorityClassName: system-node-critical
      tolerations:
      - operator: Exists
      containers:
      - name: mount-helper
        image: controller:latest
        securityContext:
          privileged: true
        volumeMounts:
        - name: host-root
          mountPath: /host
          mountPropagation: Bidirectional
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 10m
            memory: 32Mi
      volumes:
      - name: host-root
        hostPath:
          path: /
          type: Directory
