apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stoppablecontainer-system
namePrefix: stoppablecontainer-

resources:
- daemonset.yaml
- serviceaccount.yaml

images:
- name: mount-helper
  newName: stoppablecontainer-mount-helper
  newTag: e2e-test
