apiVersion: v1
kind: ServiceAccount
metadata:
  name: stoppablecontainer-mount-helper
  namespace: system
  labels:
    app.kubernetes.io/name: stoppablecontainer
    app.kubernetes.io/component: mount-helper
