apiVersion: v1
entries:
  stoppablecontainer:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2026-01-04T09:24:36.124559399Z"
    description: A Kubernetes operator for stoppable containers with persistent ephemeral
      filesystems
    digest: 4dfbc64ee21cc228312659ff23c0d875ecd401e82aeb69e905766c6f113dc6e8
    home: https://github.com/xtlsoft/stoppablecontainer
    keywords:
    - kubernetes
    - operator
    - container
    - filesystem
    - persistence
    maintainers:
    - name: xtlsoft
      url: https://github.com/xtlsoft
    name: stoppablecontainer
    sources:
    - https://github.com/xtlsoft/stoppablecontainer
    type: application
    urls:
    - https://xtlsoft.github.io/stoppablecontainer/charts/stoppablecontainer-0.1.0.tgz
    version: 0.1.0
generated: "2026-01-04T09:24:36.122182537Z"
