apiVersion: v2
name: stoppablecontainer
description: A Kubernetes operator for stoppable containers with persistent ephemeral filesystems
type: application
version: 0.1.1
appVersion: "0.1.1"
keywords:
  - kubernetes
  - operator
  - container
  - filesystem
  - persistence
home: https://github.com/xtlsoft/stoppablecontainer
sources:
  - https://github.com/xtlsoft/stoppablecontainer
maintainers:
  - name: xtlsoft
    url: https://github.com/xtlsoft
